webapp/validator/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^fields$', views.fields, name='fields'),
]

webapp/webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^validator/', include('validator.urls')),
]

webapp/validator/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
class Field(models.Model):
    key_name = models.CharField(max_length=200)
    key_category = models.CharField(max_length=200)
    key_required = models.BooleanField(default=False)
    key_help = models.TextField(blank=True)
    value_type = models.CharField(max_length=200)
    value_format = models.CharField(max_length=200, blank=True)

    @python_2_unicode_compatible
    def __str__(self):
        return ("key = " + self.key_name + " ["
                + self.value_type + "], "
                + " required = " + str(self.key_required))

webapp/validator/forms.py
from django import forms

class SigMFUploadForm(forms.Form):
    sigmf_meta_file = forms.FileField()

webapp/validator/views.py
from django.shortcuts import render
from .models import Field
from .forms import SigMFUploadForm
from django.http import HttpResponseRedirect
import sigmf

# Create your views here.

def index(request):
    global_fields = Field.objects.filter(key_category="global")
    capture_fields = Field.objects.filter(key_category="capture")
    annotations_fields = Field.objects.filter(key_category="annotations")
    categories = [{'name': "global",
                   'fields': global_fields},
                  {'name': "capture",
                   'fields': capture_fields},
                  {'name': "annotations",
                   'fields': annotations_fields}]

    sigmf_upload_form = SigMFUploadForm()
    context = {'categories': categories, 'sigmf_upload_form':
                sigmf_upload_form}

    if request.method == "POST":
        form = SigMFUploadForm(request.POST, request.FILES)
        if form.is_valid():
            print("Received valid upload")
            ul_file = request.FILES['sigmf_meta_file']
            print("File size:")
            print(ul_file.size)
            sigmf_file_str = ul_file.read()
            sigmf_file_str = sigmf_file_str.decode("utf-8")
            sigmf_validator = sigmf.SigMFFile(sigmf_file_str)
            file_is_valid = sigmf_validator.validate()
            if file_is_valid:
                context['validator_result'] = True
            else:
                print(file_is_valid.error)
                context['validator_result'] = False
                context['validator_error'] = str(file_is_valid)

            return render(request, 'validator/index.html', context)
        print("Received invalid form upload")
        return HttpResponseRedirect('/validator/')
    else:
        return render(request, 'validator/index.html', context)

def fields(request):
    global_fields = Field.objects.filter(key_category="global")
    capture_fields = Field.objects.filter(key_category="capture")
    annotations_fields = Field.objects.filter(key_category="annotations")
    categories = [{'name': "global",
                   'fields': global_fields},
                  {'name': "capture",
                   'fields': capture_fields},
                  {'name': "annotations",
                   'fields': annotations_fields}]
    context = {'categories': categories}
    return render(request, 'validator/fields.html', context)

webapp/validator/templates/validator/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head;
    any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SigMF</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="
        {% static 'validator/css/ie10-viewport-bug-workaround.css' %}"
        rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'validator/css/custom.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and
    media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js">
      </script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js">
      </script>
    <![endif]-->
    <script src=
        "https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js">
    </script>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar" aria-expanded="false"
            aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">SigMF</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}">Validator</a></li>
            <li><a href="{% url 'fields' %}">Fields</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
    {% block content %}
    {% endblock %}
    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
    </script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src=
        "{% static 'validator/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

webapp/validator/templates/validator/fields.html
{% extends "validator/base.html" %}
{% load static %}

{% block content %}
<div class="starter-template">
<h1>SigMF Fields</h1>

{% for cat in categories %}
<h2>Category {{cat.name}}</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width:30%;">
                Key
            </th>
            <th style="width:10%;">
                Type
            </th>
            <th style="width:60%;">
                Help
            </th>
        </tr>
    </thead>
    <tbody>
    {% for field in cat.fields %}
    {% if field.key_required is True %}
        <tr style="background-color:#af3e11;">
    {% else %}
        <tr>
    {% endif %}
            <th scope="row">
                {{field.key_name}}
            </th>
            <td>
                {{field.value_type}}
            </td>
            <td>
                {{field.key_help}}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endfor %}
</div>
{% endblock %}

webapp/validator/templates/validator/index.html
{% extends "validator/base.html" %}
{% load static %}

{% block content %}
<div class="starter-template">
<h1>SigMF Validator</h1>

{% if validator_result %}
    <div class="alert alert-success" role="alert">
        <h2>Your SigMF file is valid!</h2>
    </div>
{% elif validator_result == False %}
    <div class="alert alert-danger" role="alert">
        <h2>Your SigMF file is invalid!</h2>
        <p>{{validator_error}}</p>
    </div>
{% endif %}

<form action="{% url 'index' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" id="id_sigmf_meta_file" name="sigmf_meta_file"
            style="display:none;"/>
    <button type="button" id="browse" style="width:80%;height:50px;">
        Upload SigMF File
    </button>
    </br>
    <input type="submit" value="Validate!" />
</form>


</div>

<script type="text/javascript">
    $('#browse').click(function(){
        $(this).parent().find('#id_sigmf_meta_file').click();
    });
    $('#id_sigmf_meta_file').on("change", function(){
        $('#browse').html($(this).val());
    });
</script>

{% endblock %}